#include "mainwindow.h"

#include <QApplication>


/* Yatzy (GUI)
 *
 * Desc:
 * This is a yatzy game program with GUI. This game can be played with
 * multiple people limited by GUI only.
 * When you start the game each user will have 3 rolls turn. However,
 * you can give turn to other player whenever you want. But until the end
 * of the game you must finish all of your turns.
 *
 * The game logic is simple. You get "points" according to you rolls. There
 * are 5 dices in the game. And "each" possible combination has unique score
 * rank in game. You see those ranks in "functions.hh" file.
 *
 * The program terminates when everyone uses their roll turn or when "QUIT"
 * button is pressed. Then, the winner is shown in information text.
 *
 * Score board of previus games are stored as scoreBoard.txt in build file
 * generated by the program. Build file is at the same index folder as
 * the game source code file.
 *
 * Program author
 * Name: Abdullah Sagir
 * Student number: 151945467
 * UserID: nxabsa
 * E-Mail: abdulla.sagir@tuni.fi
 *
 * Notes about the program and it's implementation (if any):
 *
 * */

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.show();
    return a.exec();
}
